### ISSUE TITLE
Bug: Blank screen

### ISSUE THREAD

**Issue by Mylloon** [xy2z/PineDocs#258]
When running the docker image, nothing appears

![image](https://user-images.githubusercontent.com/29067904/192601849-0ef8217b-59e8-4dc9-9808-64ddc557e360.png)

No errors in the browser console and in the container logs, the index.html is completely empty

**Comment by xy2z** [comment]
Hmm weird, how did you run the docker?

**Comment by Mylloon** [comment]
With docker compose :
```compose
version: '3'

services:
  web:
    build: .
    ports:
      - 3000:80
    volumes:
      - /home/me/PineDocs/config:/data/pinedocs/config
      - /home/me/files:/data/pinedocs/files
```
usually it works, but for no reason it doesn't work anymore, it's super weird
however it works without docker

I tried with docker run, same result

**Comment by Mylloon** [comment]
Looks like an error with the path for my files

**Comment by Mylloon** [comment]
Found it! I created this morning a virtualenv with Python in a subfolder, that's the cause of this bug

**Comment by xy2z** [comment]
ah i thought you were using the "official" docker image

**Comment by Mylloon** [comment]
Hm I have the same issue with the official one

**Comment by xy2z** [comment]
can you share your docker-compose?

**Comment by xy2z** [comment]
btw in the screenshot you are on port 3001 but in the docker-compose it's on port 3000

**Comment by Mylloon** [comment]
```
version: '3'

services:
  web:
    image: xy2z/pinedocs:1.2.5
    ports:
      - 3000:80
    volumes:
      - /home/anri/PineDocs/config:/data/pinedocs/config
      - /home/anri/Cours:/data/pinedocs/files
```
Screenshot (with python venv bin/python symlinks)
![image](https://user-images.githubusercontent.com/29067904/192643571-3a7965c3-4171-419f-b6d0-fdfb9be0df32.png)

So yeah definitely working when I delete thoses files
